services:
    sakonnin.messages:
        class: BisonLab\SakonninBundle\Service\Messages
        arguments: ['@service_container' ]

    sakonnin.listener:
        class: BisonLab\SakonninBundle\EventListener\ChangeTracker
        calls: 
            - [ setContainer, ['@service_container'] ]
        tags:
            - { name: doctrine.event_listener, event: postFlush  }
            - { name: doctrine.event_listener, event: onFlush  }
