services:
    _defaults: { public: true }

    sakonnin.messages:
        class: BisonLab\SakonninBundle\Service\Messages
        arguments: ['@service_container' ]

    sakonnin.files:
        class: BisonLab\SakonninBundle\Service\Files
        arguments: ['@service_container' ]

    sakonnin.functions:
        class: BisonLab\SakonninBundle\Service\Functions
        arguments: ['@service_container', '%sakonnin.function_factories%']

    sakonnin.templates:
        class: BisonLab\SakonninBundle\Service\Templates
        arguments: ['@service_container' ]

    sakonnin.securitymodel_voter:
        class: BisonLab\SakonninBundle\Service\SecurityModelVoter
        arguments: ['@external_retriever' ]
        public: false
        tags:
            - { name: security.voter }

    sakonnin.file_listener:
        class: BisonLab\SakonninBundle\EventListener\SakonninFileListener
        arguments: ['%sakonnin.file_storage%']
        public: false
        tags:
            - { name: doctrine.event_listener, event: preRemove  }
            - { name: doctrine.event_listener, event: postRemove  }

    sakonnin_messages:
        alias: sakonnin.messages

    sakonnin_functions:
        alias: sakonnin.functions

    # Should this be here at all? It's kinda optional.
    # Answer: No. Put it in your local app/config/services.yml if you are going
    # to use it.
    # Add the sakonnin.sms: parameters needed by your handler in parameters.yml
    # or config.yml. Or even in service.yml itself. (But remember; no
    # passwords, they belong in parameters.yml and not your versioning system.
    #sakonnin.sms_handler:
    #    class: BisonLab\SakonninBundle\Service\SmsHandler
    #    arguments: 
    #        container: '@service_container'
    #        options: '%sakonnin.sms%'
