services:
    sakonnin.messages:
        class: BisonLab\SakonninBundle\Service\Messages
        arguments: ['@service_container' ]

    sakonnin.functions:
        class: BisonLab\SakonninBundle\Service\Functions
        arguments: 
            container: '@service_container'
            function_classes: "%sakonnin.function_factories%"

    # Should this be here at all? It's kinda optional.
    sakonnin.sms_handler:
        class: BisonLab\SakonninBundle\Service\SmsHandler
        arguments: 
            container: '@service_container'
            options: '%sakonnin.sms%'
