services:
    sakonnin.messages:
        class: BisonLab\SakonninBundle\Service\Messages
        arguments: ['@service_container' ]

    sakonnin.functions:
        class: BisonLab\SakonninBundle\Service\Functions
        arguments: 
            container: '@service_container'
            function_classes: %sakonnin.function_factories%

    sakonnin.listener:
        class: BisonLab\SakonninBundle\EventListener\ChangeTracker
        calls: 
            - [ setContainer, ['@service_container'] ]
        tags:
            - { name: doctrine.event_listener, event: postFlush  }
            - { name: doctrine.event_listener, event: onFlush  }

    sakonnin.form.type.function_attribute:
        class: BisonLab\SakonninBundle\Form\FunctionAttributeType
        tags:
            - { name: form.type, alias: function_attribute }
        
    
