parameters:
    sakonnin.address_types:
        EMAIL:
            chooseable: true
        INTERNAL:
            chooseable: true
        SMS:
            chooseable: true
        REST:
            chooseable: false

