parameters:
    # Base message types.
    # States is the common order they are set. Default is the first one in the
    # list.
    sakonnin.base_types:
        MESSAGE:
            states: ['UNREAD', 'READ']
            short: "Message"
            description: "Messages with to, from, subject and body"
        NOTE:
            states: ['UNREAD', 'READ']
            short: "Note"
            description: "Notes attached to a context (object)"
        CHECK:
            states: ['UNCHECKED', 'CHECKED']
            short: "Checkitem"
            description: "Check(list) item"
    sakonnin.address_types:
        # None at all. Notes uses createdBy and contexts.
        NONE:
            chooseable: true
        # PMs - I Wish I used "USERID" as type. As it *is* an address type.
        # TODO: Change to USERID.
        INTERNAL:
            chooseable: true
        # Good old SMTP. (Or POP or IMAP if we pull them ourselves.)
        EMAIL:
            chooseable: true
        # Yup, text message.
        SMS:
            chooseable: true
        # Posted via the MessageController. Used as default if none else is
        # posted in the create.
        EXTERNAL:
            chooseable: false

    # The simplest file types.
    sakonnin.file_types:
        IMAGE:
            chooseable: true
        VIDEO:
            chooseable: true
        TEXT:
            chooseable: true
        DOCUMENT:
            chooseable: true
        PRESENTATION:
            chooseable: true
        SPREADSHEET:
            chooseable: true
        BINARY:
            chooseable: true
        UNKNOWN:
            chooseable: true
