<?php

namespace BisonLab\SakonninBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTypeRepository extends EntityRepository
{
    public function getTypesAsChoiceArray($preferred = array())
    {

        $dql = '
SELECT mt
FROM BisonLab\SakonninBundle\Entity\MessageType mt
WHERE mt.parent is null
';

        $query = $this->_em->createQuery($dql);
        $groups = array();
        $res = $query->getResult();
        foreach ($res as $r) {
            $types = array(); 
            foreach ($r->getChildren() as $c) {
                if (in_array($c, $preferred))
                    $types[$c->getName()] = true;
                else 
                    $types[$c->getName()] = false;
            }
            $groups[$r->getName()] = $types;
        }
        ksort($groups);
        return $groups;

    }
}
