<?php

namespace BisonLab\SakonninBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

use BisonLab\SakonninBundle\Entity\MessageType;

/**
 * MessageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTypeRepository extends ServiceEntityRepository
{
    /**
     * @param ManagerRegistry $managerRegistry
     */
    public function __construct(ManagerRegistry $managerRegistry)
    {
        parent::__construct($managerRegistry, MessageType::class);
    }

    public function getTypesAsChoiceArray($preferred = array())
    {

        $dql = '
SELECT mt
FROM BisonLab\SakonninBundle\Entity\MessageType mt
WHERE mt.parent is null
';

        $query = $this->getEntityManager()->createQuery($dql);
        $groups = array();
        $res = $query->getResult();
        foreach ($res as $r) {
            $types = array(); 
            foreach ($r->getChildren() as $c) {
                if (in_array($c, $preferred))
                    $types[$c->getName()] = true;
                else 
                    $types[$c->getName()] = false;
            }
            $groups[$r->getName()] = $types;
        }
        ksort($groups);
        return $groups;
    }
}
