<?php

namespace BisonLab\SakonninBundle\Repository;

use BisonLab\CommonBundle\Entity\ContextBaseRepository;

/**
 * FileContextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileContextRepository extends ContextBaseRepository
{
    /*
     * This should explain itself, but the context here is of course not a
     * FileContext entity, but the keys to find one. And the answer to the
     * question is easy, if there are one or more FileContexts, there are
     * files.
     */
    public function contextHasFiles($context_data)
    {
        $qb2 = $this->_em->createQueryBuilder();
        $qb2->select('mc')
              ->from($this->_entityName, 'mc')
              ->where('mc.system = :system')
              ->andWhere('mc.object_name = :object_name')
              ->andWhere('mc.external_id = :external_id')
              ->setParameter("system", $context_data['system'])
              ->setParameter("object_name", $context_data['object_name'])
              ->setParameter("external_id", $context_data['external_id'])
              ->setMaxResults(1);

        $file_context = $qb2->getQuery()->getResult();
        return !empty($file_context);
    }
}
