<?php

namespace BisonLab\SakonninBundle\Repository;

/**
 * SakonninFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SakonninFileRepository extends \Doctrine\ORM\EntityRepository
{
}
