<?php

namespace BisonLab\SakonninBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SakonninTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SakonninTemplateRepository extends EntityRepository
{
    public function getTypesAsChoiceArray($preferred = array())
    {
    }
}
