services:
    _defaults: { public: true }

    BisonLab\SakonninBundle\Command\:
        resource: '../Command/*'
        arguments: ['@service_container' ]
        tags: ['console.command']

    BisonLab\SakonninBundle\Controller\:
        resource: '../Controller/*'
        tags: ['controller.service_arguments']
        # AbstractController still needs this!
        calls:
            - [ setContainer, ['@service_container'] ]
            - [ setFormFactory, ['@form.factory'] ]
            - [ setSakonninMessages, ['@sakonnin.messages'] ]
            - [ setSakonninFunctions, ['@sakonnin.functions'] ]

    BisonLab\SakonninBundle\Repository\:
        resource: '../Repository/*'
        autowire: true
        tags: ['doctrine.repository_service']

    sakonnin.messages:
        class: BisonLab\SakonninBundle\Service\Messages
        arguments: ['@service_container' ]
        calls:
            - [ setMailer, ['@mailer.mailer'] ]

    sakonnin.files:
        class: BisonLab\SakonninBundle\Service\Files
        arguments: ['@service_container' ]

    sakonnin.functions:
        class: BisonLab\SakonninBundle\Service\Functions
        arguments: ['@service_container', '%sakonnin.function_factories%']
        calls:
            - [ setMailer, ['@mailer.mailer'] ]

    sakonnin.templates:
        class: BisonLab\SakonninBundle\Service\Templates
        arguments: ['@service_container' ]

    sakonnin.securitymodel_voter:
        class: BisonLab\SakonninBundle\Service\SecurityModelVoter
        arguments: ['@bisonlab_context.external_retriever', '@sakonnin.messages']
        public: false
        tags:
            - { name: security.voter }

    sakonnin.file_listener:
        class: BisonLab\SakonninBundle\EventListener\SakonninFileListener
        arguments: ['%sakonnin.file_storage%']
        public: false
        tags:
            - { name: doctrine.event_listener, event: preRemove  }
            - { name: doctrine.event_listener, event: postRemove  }

    sakonnin_messages:
        alias: sakonnin.messages
        deprecated:
            package: 'bisonlab/sakonnin-bundle'
            version: '4.0'
            message: 'The "%alias_id%" alias is deprecated. Use sakonnin.messages'

    sakonnin_functions:
        alias: sakonnin.functions
        deprecated:
            package: 'bisonlab/sakonnin-bundle'
            version: '4.0'
            message: 'The "%alias_id%" alias is deprecated. Use sakonnin.functions'

    # Should this be here at all? It's kinda optional.
    # Answer: No. Put it in your local app/config/services.yml if you are going
    # to use it.
    # Add the sakonnin.sms: parameters needed by your handler in parameters.yml
    # or config.yml. Or even in service.yml itself. (But remember; no
    # passwords, they belong in parameters.yml and not your versioning system.
    #sakonnin.sms_handler:
    #    class: BisonLab\SakonninBundle\Service\SmsHandler
    #    arguments: 
    #        container: '@service_container'
    #        options: '%sakonnin.sms%'
